set -g default-terminal "tmux-256color"
unbind C-b
set-option -g prefix C-a
bind-key C-a last-window
bind-key a send-prefix
bind-key C-c new-window
bind-key Space next-window
bind-key C-Space next-window
set-option -g status-bg white
set-option -g status-fg black
set-option -g status-right "#h"
set-option -sg escape-time 40
set-option -g set-titles on
set -g set-titles-string "#T"
